//Copyright (C)2014-2026 GOWIN Semiconductor Corporation.
//All rights reserved.
//File Title: Timing Constraints file
//Tool Version: V1.9.12.01 (64-bit) 
//Created Time: 2026-09-10 11:25:54
create_clock -name clk_in -period 20 -waveform {0 10} [get_ports {clk_in_p}]
create_clock -name data_out_clk -period 6.667 -waveform {0 3.333} [get_ports {dco}]
set_clock_groups -asynchronous -group [get_clocks {clk_in}] -group [get_clocks {data_out_clk}]
set_output_delay -clock data_out_clk -2.8 -max [get_ports {ch1_data_out[15] ch1_data_out[14] ch1_data_out[13] ch1_data_out[12] ch1_data_out[11] ch1_data_out[10] ch1_data_out[9] ch1_data_out[8] ch1_data_out[7] ch1_data_out[6] ch1_data_out[5] ch1_data_out[4] ch1_data_out[3] ch1_data_out[2] ch1_data_out[1] ch1_data_out[0]}]
set_multicycle_path -from [get_pins {u_register_block/addr_dly_0_s0/Q u_register_block/addr_dly_1_s0/Q u_register_block/addr_dly_2_s0/Q u_register_block/addr_dly_3_s0/Q u_register_block/addr_dly_4_s0/Q u_register_block/addr_dly_5_s0/Q u_register_block/addr_dly_6_s0/Q}] -to [get_pins {u_register_block/data_out_0_s0/D u_register_block/data_out_10_s0/D u_register_block/data_out_11_s0/D u_register_block/data_out_12_s0/D u_register_block/data_out_13_s0/D u_register_block/data_out_14_s0/D u_register_block/data_out_15_s0/D u_register_block/data_out_1_s0/D u_register_block/data_out_2_s0/D u_register_block/data_out_3_s0/D u_register_block/data_out_4_s0/D u_register_block/data_out_5_s0/D u_register_block/data_out_6_s0/D u_register_block/data_out_7_s0/D u_register_block/data_out_8_s0/D u_register_block/data_out_9_s0/D}]  -setup -end 2
set_multicycle_path -from [get_pins {u_register_block/addr_dly_0_s0/Q u_register_block/addr_dly_1_s0/Q u_register_block/addr_dly_2_s0/Q u_register_block/addr_dly_3_s0/Q u_register_block/addr_dly_4_s0/Q u_register_block/addr_dly_5_s0/Q u_register_block/addr_dly_6_s0/Q}] -to [get_pins {u_register_block/data_out_0_s0/D u_register_block/data_out_10_s0/D u_register_block/data_out_11_s0/D u_register_block/data_out_12_s0/D u_register_block/data_out_13_s0/D u_register_block/data_out_14_s0/D u_register_block/data_out_15_s0/D u_register_block/data_out_1_s0/D u_register_block/data_out_2_s0/D u_register_block/data_out_3_s0/D u_register_block/data_out_4_s0/D u_register_block/data_out_5_s0/D u_register_block/data_out_6_s0/D u_register_block/data_out_7_s0/D u_register_block/data_out_8_s0/D u_register_block/data_out_9_s0/D}]  -hold -end 1
