/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'arm_fft_bin_example' 
 * Target:  'ARMCM55_FP_MVE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM55.h"



#endif /* RTE_COMPONENTS_H */
